### ISSUE TITLE
함수에 질문이 있습니다. 

### ISSUE THREAD

**Issue by mingtian-chan** [kookmin-sw/capstone-2023-04#16]
https://github.com/kookmin-sw/capstone-2023-04/blob/def56fce666159ae46562e74c3b09853cddb7f28/backend/web_server/station/routers.py#L5

각 함수는 데이터베이스에 접근하는 함수인 것 같은데, **hint 라는 인자는 어떤 역할을 하나요?

**Comment by mumat0103** [comment]
인스턴스 존재여부를 판단하는 인자라고 합니다.

**Comment by mingtian-chan** [comment]
확인했습니다.
