### ISSUE TITLE
Result page 백엔드 연결

### ISSUE THREAD

**Issue by mingtian-chan** [kookmin-sw/capstone-2023-04#37]
main.js 41줄 처럼 정보 받아오면 받아온 것 만큼 Pathindex를 만들어서 보여주면 됨.

https://github.com/kookmin-sw/capstone-2023-04/blob/9f965e397b6bc044d33e381b272b9067ebd0d77a/frontend/src/pages/Result/Result.js#L12

**Comment by mumat0103** [comment]
완료
