### ISSUE TITLE
Pathindex component  백엔드 연결

### ISSUE THREAD

**Issue by mingtian-chan** [kookmin-sw/capstone-2023-04#39]
- [x] 버스 정보를 받아오면 bus_index가 처리되어 bus_color가 정해집니다.
백엔드에서 정보만 받아오면 됨.

https://github.com/kookmin-sw/capstone-2023-04/blob/9f965e397b6bc044d33e381b272b9067ebd0d77a/frontend/src/components/Pathindex/Pathindex.js#L9

- [x] 타는 대중교통에 맞게 img_Idx만 바꾸면 됩니다. 
https://github.com/kookmin-sw/capstone-2023-04/blob/9f965e397b6bc044d33e381b272b9067ebd0d77a/frontend/src/components/Pathindex/Pathindex.js#L22

- [x] 걸리는 시간을 서버에서 받아서 현재 "30"으로 적혀있는 숫자 부분에 넣어주세요
https://github.com/kookmin-sw/capstone-2023-04/blob/9f965e397b6bc044d33e381b272b9067ebd0d77a/frontend/src/components/Pathindex/Pathindex.js#L32

- [x] "출발지 이름" 부분에 서버에서 출발지를 받아와 넣어주세요 
https://github.com/kookmin-sw/capstone-2023-04/blob/9f965e397b6bc044d33e381b272b9067ebd0d77a/frontend/src/components/Pathindex/Pathindex.js#L39

- [x] 버스 번호
https://github.com/kookmin-sw/capstone-2023-04/blob/9f965e397b6bc044d33e381b272b9067ebd0d77a/frontend/src/components/Pathindex/Pathindex.js#L50

- [x] 정류장 이름
https://github.com/kookmin-sw/capstone-2023-04/blob/9f965e397b6bc044d33e381b272b9067ebd0d77a/frontend/src/components/Pathindex/Pathindex.js#L52

- [x] 도착지 이름
https://github.com/kookmin-sw/capstone-2023-04/blob/9f965e397b6bc044d33e381b272b9067ebd0d77a/frontend/src/components/Pathindex/Pathindex.js#L56

**Comment by mumat0103** [comment]
완료
